# Generated by Django 4.2.6 on 2023-10-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredeproducto', models.CharField(max_length=200)),
                ('cantidad', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredeusuario', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadcomprar', models.IntegerField()),
                ('totalpagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iddeproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productos')),
                ('iddeusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='iddeusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuarios'),
        ),
    ]
